
version: 0.0
os: linux

files:
  - source: ./
    destination: /var/www/html/

permissions:
  - object: /var/www/html/
    pattern: "**"
    owner: ec2-user
    mode: 644
    type:
      - file
hooks:
  ApplicationStop:
    - location: /scripts/stop_server.sh
      timeout: 300
  AfterInstall:
    - location: /scripts/start_server.sh
      timeout: 300
    - location: /scripts/write_file.sh
      timeout: 300
      
